services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_planner
      POSTGRES_USER: task_planner_user
      POSTGRES_PASSWORD: task_planner_password
    volumes:
      - task_planner_pg_data:/var/lib/postgresql/data

volumes:
  task_planner_pg_data:
